export const GET_MOVIE_DATA_REQUEST = "GET_MOVIE_DATA_REQUEST";
export const GET_MOVIE_DATA_SUCCESS = "GET_MOVIE_DATA_SUCCESS";
export const GET_MOVIE_DATA_ERROR = "GET_MOVIE_DATA_ERROR";

export const GET_MOVIE_LIST_REQUEST = "GET_MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_ERROR = "GET_MOVIE_LIST_ERROR";

export const RESET_MOVIE_DATA = "RESET_MOVIE_DATA";
